language: node_js
branches:
  only:
    - testing/e2e
    - master
    - release
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod
  - npx cypress run 
  - npm run build
deploy:
  - skip_cleanup: true
  - provider: script
    script:
      - npm run report-coverage
      - npm run deploy-docs
      - npm run semantic-release
    on:
      branch: release
