language: node_js
branches:
  only:
    - master
    - testing/e2e
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod
  - npx capacitor run 
  - npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
